services:
  postgres:
    image: postgres:16
    container_name: compound-postgres
    environment:
      POSTGRES_DB: compound_chemistry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:latest
    container_name: compound-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"      # S3 API
      - "9001:9001"      # MinIO Console
    volumes:
      - ./uploads:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./minio-init.sh:/minio-init.sh:ro
      - ./minio-cors.xml:/minio-cors.xml:ro
    entrypoint: /bin/sh /minio-init.sh
